extern char WB_inst_key[];
extern char Database_str[];
extern char Path_str[];
extern char ClientMem_str[];
extern char ServerMem_str[];
extern char SortSpace_str[];
extern char TotalSort_str[];
extern char FrameSpace_str[];
extern char ClientProt_str[];
extern char KeepAlive_str[];
extern char IP_str[];
extern char IP_socket_str[];
extern char FWIP_str[];
extern char viaFW_str[];
extern char useTunnel_str[];
extern char Conn_str[];
extern char Broadcast_str[];
extern char Version_str[];
extern char FIL_version_supported[];
extern char Licen_str[];
extern char Expir_str[];
extern char Pcache_str[];
extern char Pcchdir_str[];
extern char ODBCProt_str[];
extern char DisAnon_str[];
extern char database_ik[];
#define IP_ADDR_MAX  100

